# A readapter pour le projet

# variables:
#   TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
#   TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

# stages:
#   - build
#   - test

# job_build:
#   image: node:lts-alpine
#   stage: build
#   script:
#     - echo "Building the project"
#     - cd front-end
#     - yarn install
#     - yarn build
#     - echo "Build completed"

# job_test:
#   stage: test
#   script:
#     - echo "Running tests"