variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - test

job_build:
  image: node:lts-alpine
  stage: build
  script:
    - echo "Building the project"
    - echo "Build step simulated"
    - echo "Build completed"

job_test:
  image: node:lts-alpine
  stage: test

  script:
    - echo "Running tests for backend"
    - cd rxapa-hcp-server && npm install && npm test
    - echo "Running tests for frontend"
    - cd ../rxapa-hcp-client && npm install && npm test
