version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000"
    expose:
      - 3000
    networks:
      - webnet
  web:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8081"
    expose:
      - 8081
    depends_on:
      - server
    networks:
      - webnet
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - server
    networks:
      - webnet

networks:
  webnet:
