version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
  web:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:8081"
    expose:
      - 8081
    depends_on:
      - server
