FROM --platform=linux/amd64 node
# FROM node:14-alpine

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . ./

ENV DATABASE_NAME=''
ENV DATABASEL_USER=''
ENV DATABASE_PASSWORD=''
ENV DATABASE_URL=""

EXPOSE 80

CMD ["npm", "start"]
